"""add_model_answer_expected_answer_to_eval_runs

Revision ID: ef7048c18bba
Revises: 07222cc627f3
Create Date: 2026-03-25 17:22:25.118334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ef7048c18bba'
down_revision: Union[str, None] = '07222cc627f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eval_runs', sa.Column('expected_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('eval_runs', sa.Column('model_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('eval_runs', 'ground_truth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eval_runs', sa.Column('ground_truth', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('eval_runs', 'model_answer')
    op.drop_column('eval_runs', 'expected_answer')
    # ### end Alembic commands ###
